variables:
  MAVEN_REPO_DIR: $CI_PROJECT_DIR/.m2/repository
  MAVEN_IMAGE: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3.9-eclipse-temurin-8
  DOCKER_COMPOSE_IMAGE: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker/compose
  MAVEN_OPTS: >-
    -Xmx256m
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$MAVEN_REPO_DIR
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --settings=$MVN_SETTINGS
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  BUILD_VERSION: ${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
  RELEASE_VERSION: ${BUILD_VERSION}

services:
  - name: docker:dind
    command: [ "--tls=false" ]

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - deploy

image: ${MAVEN_IMAGE}

cache:
  paths:
    - $MAVEN_REPO_DIR

utest:backend:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  artifacts:
    when: always
    reports:
      junit:
        - '**/target/surefire-reports/*.xml'

#.deploy:
#  stage: deploy
#  image: ${MAVEN_IMAGE}
#  rules:
#    - when: always
#  needs:
#    - utest:backend
#  script:
#    - 'mvn $MAVEN_CLI_OPTS clean compile deploy -DskipTests=true -Pforeach -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true'
#
#deploy:snapshot:
#  extends:
#    - .deploy
#  environment:
#    name: snapshot

.deploy:
  stage: deploy
  variables:
    TZ: "UTC" # Generally recommended for reproducible builds, and we're skipping tests in this job anyway.
  before_script:
    - if [[ -f ci-before.sh ]]; then ./ci-before.sh; fi
    - apt-get update
    - apt-get -y install gpg
    - gpg --pinentry-mode loopback --passphrase $ACROSS_GPG_PASSPHRASE --import $ACROSS_GPG_PRIVATE_KEY
    - gpg --list-keys
  script:
    # For reproducible builds, we have to run the build twice:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
    - mvn $MAVEN_CLI_OPTS clean verify artifact:compare -DskipTests
    - mvn $MAVEN_CLI_OPTS --settings ci_settings.xml --activate-profiles deploy,$MAVEN_PROFILE deploy -DskipTests

deploy:foreach:
  extends:
    - .deploy
  variables:
    MAVEN_PROFILE: foreach
  rules:
    - if: $CI_COMMIT_TAG == null

deploy:sonatype:
  extends:
    - .deploy
  variables:
    MAVEN_PROFILE: sonatype
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
