spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:../local-data/db/file-manager-module
    username: sa
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

across:
  development:
    active: true

adminWebModule:
  title: Admin FMM
  login:
    rememberMe:
      key: filemanagermodule
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

acrossModule:
  FileManagerModule:
    resources: ../file-manager-module/src/main/resources

fileManagerModule:
  expiration:
    enabled: true
    interval-seconds: 30
  local-repositories-root: "../local-data/storage"

acrossHibernate:
  properties:
    hibernate.hbm2ddl.auto: update

ftp1:
  username: stg
  password: pw
  port: 21
  host: localhost

sftp1:
  username: demo
  password: demo
  port: 22
  host: localhost